services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
    command: ["npm", "start"]

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app:cached
    command: ["node", "index.js"]
